version: '3'

services:
  jibber-jabber-messages-db:
    container_name: messagesDB
    image: postgres:12
    restart: always
    env_file:
      - .env.production
    ports:
      - 5435:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  jibber-jabber-messages-api:
    container_name: api-messages
#    image: jibber-jabber-messages_api #Queda buildeada del docker-compose build, eventualmente pusheada en un repo publico.
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8003:8003
    env_file:
      - .env.production
    depends_on:
      - jibber-jabber-messages-db

volumes:
  pgdata: